// Mock data for Harvestá Marketplace
import type { 
  CartGroup, 
  Vendor, 
  Product, 
  DeliveryOption, 
  PaymentMethod, 
  Order, 
  BuyerInfo, 
  DeliveryAddress,
  Category,
  SupplierProfile,
  Review,
  OrderTracking
} from '@/types/marketplace';

export const mockVendors: Vendor[] = [
  {
    id: 'v1',
    name: 'Green Valley Farms',
    rating: 4.8,
    totalSales: 15420,
    location: 'Nakuru, Kenya',
    isVerified: true,
    isQualityChecked: true,
    responseTime: '< 2 hours',
  },
  {
    id: 'v2',
    name: 'Sunshine Agro Ltd',
    rating: 4.6,
    totalSales: 8930,
    location: 'Accra, Ghana',
    isVerified: true,
    isQualityChecked: false,
    responseTime: '< 4 hours',
  },
  {
    id: 'v3',
    name: 'Harvest Gold Exporters',
    rating: 4.9,
    totalSales: 23100,
    location: 'Lagos, Nigeria',
    isVerified: true,
    isQualityChecked: true,
    responseTime: '< 1 hour',
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Premium Arabica Coffee Beans',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop',
    category: 'Grains',
    grade: 'Grade AA',
    origin: 'Mount Kenya Region',
    unit: 'kg',
    moq: 50,
    pricingTiers: [
      { minQuantity: 50, maxQuantity: 199, pricePerUnit: 12.50 },
      { minQuantity: 200, maxQuantity: 499, pricePerUnit: 11.00 },
      { minQuantity: 500, maxQuantity: null, pricePerUnit: 9.50 },
    ],
    currentPrice: 12.50,
    originalPrice: 15.00,
  },
  {
    id: 'p2',
    name: 'Fresh Organic Avocados',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop',
    category: 'Fruits',
    grade: 'Export Quality',
    origin: "Murang'a, Kenya",
    unit: 'crate (50 pcs)',
    moq: 10,
    pricingTiers: [
      { minQuantity: 10, maxQuantity: 49, pricePerUnit: 45.00 },
      { minQuantity: 50, maxQuantity: 99, pricePerUnit: 40.00 },
      { minQuantity: 100, maxQuantity: null, pricePerUnit: 35.00 },
    ],
    currentPrice: 45.00,
  },
  {
    id: 'p3',
    name: 'Golden Cocoa Beans',
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&h=400&fit=crop',
    category: 'Grains',
    grade: 'Grade A Fermented',
    origin: 'Ashanti Region, Ghana',
    unit: 'kg',
    moq: 100,
    pricingTiers: [
      { minQuantity: 100, maxQuantity: 499, pricePerUnit: 8.00 },
      { minQuantity: 500, maxQuantity: 999, pricePerUnit: 7.20 },
      { minQuantity: 1000, maxQuantity: null, pricePerUnit: 6.50 },
    ],
    currentPrice: 8.00,
    originalPrice: 9.50,
  },
  {
    id: 'p4',
    name: 'Dried Hibiscus Flowers (Zobo)',
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400&h=400&fit=crop',
    category: 'Vegetables',
    grade: 'Premium Dried',
    origin: 'Kano, Nigeria',
    unit: 'kg',
    moq: 25,
    pricingTiers: [
      { minQuantity: 25, maxQuantity: 99, pricePerUnit: 6.00 },
      { minQuantity: 100, maxQuantity: 499, pricePerUnit: 5.00 },
      { minQuantity: 500, maxQuantity: null, pricePerUnit: 4.20 },
    ],
    currentPrice: 6.00,
  },
  {
    id: 'p5',
    name: 'Organic Shea Butter (Raw)',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop',
    category: 'Agro-inputs',
    grade: 'Grade A Unrefined',
    origin: 'Northern Ghana',
    unit: 'kg',
    moq: 20,
    pricingTiers: [
      { minQuantity: 20, maxQuantity: 99, pricePerUnit: 15.00 },
      { minQuantity: 100, maxQuantity: 499, pricePerUnit: 13.00 },
      { minQuantity: 500, maxQuantity: null, pricePerUnit: 11.00 },
    ],
    currentPrice: 15.00,
    originalPrice: 18.00,
  },
  {
    id: 'p6',
    name: 'Fresh Cassava Tubers',
    image: 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=400&h=400&fit=crop',
    category: 'Tubers',
    grade: 'Grade A',
    origin: 'Ogun State, Nigeria',
    unit: 'ton',
    moq: 5,
    pricingTiers: [
      { minQuantity: 5, maxQuantity: 19, pricePerUnit: 180.00 },
      { minQuantity: 20, maxQuantity: 49, pricePerUnit: 160.00 },
      { minQuantity: 50, maxQuantity: null, pricePerUnit: 140.00 },
    ],
    currentPrice: 180.00,
  },
  {
    id: 'p7',
    name: 'Premium Maize (Yellow Corn)',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=400&fit=crop',
    category: 'Grains',
    grade: 'Grade 1',
    origin: 'Rift Valley, Kenya',
    unit: 'bag (90kg)',
    moq: 50,
    pricingTiers: [
      { minQuantity: 50, maxQuantity: 199, pricePerUnit: 35.00 },
      { minQuantity: 200, maxQuantity: 499, pricePerUnit: 32.00 },
      { minQuantity: 500, maxQuantity: null, pricePerUnit: 28.00 },
    ],
    currentPrice: 35.00,
    originalPrice: 40.00,
  },
  {
    id: 'p8',
    name: 'Organic Tomatoes',
    image: 'https://images.unsplash.com/photo-1546470427-227c7eb5cf00?w=400&h=400&fit=crop',
    category: 'Vegetables',
    grade: 'Fresh Harvest',
    origin: 'Brong Ahafo, Ghana',
    unit: 'crate (25kg)',
    moq: 20,
    pricingTiers: [
      { minQuantity: 20, maxQuantity: 49, pricePerUnit: 22.00 },
      { minQuantity: 50, maxQuantity: 99, pricePerUnit: 19.00 },
      { minQuantity: 100, maxQuantity: null, pricePerUnit: 16.00 },
    ],
    currentPrice: 22.00,
  },
];

export const mockDeliveryOptions: DeliveryOption[] = [
  {
    id: 'd1',
    type: 'pickup',
    name: 'Warehouse Pickup',
    estimatedDays: { min: 1, max: 2 },
    cost: 0,
  },
  {
    id: 'd2',
    type: 'vendor_delivery',
    name: 'Vendor Delivery',
    estimatedDays: { min: 3, max: 5 },
    cost: 25.00,
    freeAbove: 500,
  },
  {
    id: 'd3',
    type: 'third_party',
    name: 'DHL Express',
    estimatedDays: { min: 2, max: 4 },
    cost: 45.00,
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: 'pm1',
    type: 'mobile_money',
    name: 'M-Pesa',
    icon: '📱',
    details: 'Pay via M-Pesa mobile money',
  },
  {
    id: 'pm2',
    type: 'mobile_money',
    name: 'MTN Mobile Money',
    icon: '📱',
    details: 'Pay via MTN MoMo',
  },
  {
    id: 'pm3',
    type: 'bank_transfer',
    name: 'Bank Transfer',
    icon: '🏦',
    details: 'Direct bank transfer',
  },
  {
    id: 'pm4',
    type: 'cash_on_delivery',
    name: 'Cash on Delivery',
    icon: '💵',
    details: 'Pay when you receive your order (local only)',
  },
];

export const mockCartGroups: CartGroup[] = [
  {
    vendor: mockVendors[0],
    items: [
      {
        id: 'ci1',
        product: mockProducts[0],
        vendor: mockVendors[0],
        quantity: 100,
      },
      {
        id: 'ci2',
        product: mockProducts[1],
        vendor: mockVendors[0],
        quantity: 20,
      },
    ],
    deliveryOptions: mockDeliveryOptions,
    selectedDeliveryOption: mockDeliveryOptions[1],
    subtotal: 2150.00,
  },
  {
    vendor: mockVendors[1],
    items: [
      {
        id: 'ci3',
        product: mockProducts[4],
        vendor: mockVendors[1],
        quantity: 50,
      },
    ],
    deliveryOptions: mockDeliveryOptions,
    selectedDeliveryOption: mockDeliveryOptions[2],
    subtotal: 650.00,
  },
  {
    vendor: mockVendors[2],
    items: [
      {
        id: 'ci4',
        product: mockProducts[2],
        vendor: mockVendors[2],
        quantity: 200,
      },
      {
        id: 'ci5',
        product: mockProducts[3],
        vendor: mockVendors[2],
        quantity: 100,
      },
    ],
    deliveryOptions: mockDeliveryOptions,
    selectedDeliveryOption: mockDeliveryOptions[0],
    subtotal: 1940.00,
  },
];

export const mockBuyerInfo: BuyerInfo = {
  type: 'business',
  firstName: 'John',
  lastName: 'Kamau',
  email: 'john@afritradefoods.com',
  phone: '+254 712 345 678',
  companyName: 'AfriTrade Foods Ltd',
  taxId: 'KRA-12345678',
  contactPerson: 'John Kamau',
};

export const mockDeliveryAddress: DeliveryAddress = {
  id: 'addr1',
  label: 'Main Warehouse',
  street: '45 Industrial Area, Mombasa Road',
  city: 'Nairobi',
  state: 'Nairobi County',
  country: 'Kenya',
  postalCode: '00100',
  isDefault: true,
};

export const mockOrder: Order = {
  id: 'ord1',
  orderNumber: 'HRV-2026-0107-001',
  createdAt: new Date().toISOString(),
  status: 'confirmed',
  paymentStatus: 'pending',
  buyer: mockBuyerInfo,
  deliveryAddress: mockDeliveryAddress,
  groups: mockCartGroups,
  subtotal: 4740.00,
  deliveryTotal: 70.00,
  taxes: 379.20,
  grandTotal: 5189.20,
  paymentMethod: mockPaymentMethods[0],
};

export const mockCategories: Category[] = [
  {
    id: 'cat1',
    name: 'Grains',
    slug: 'grains',
    icon: '🌾',
    description: 'High-quality grains including maize, wheat, rice, sorghum, and millets from verified African farms.',
    subCategories: [
      { id: 'sub1', name: 'Maize', slug: 'maize', productCount: 234 },
      { id: 'sub2', name: 'Wheat', slug: 'wheat', productCount: 156 },
      { id: 'sub3', name: 'Rice', slug: 'rice', productCount: 189 },
      { id: 'sub4', name: 'Sorghum', slug: 'sorghum', productCount: 87 },
      { id: 'sub5', name: 'Millet', slug: 'millet', productCount: 62 },
    ],
    productCount: 728,
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&h=400&fit=crop',
  },
  {
    id: 'cat2',
    name: 'Tubers',
    slug: 'tubers',
    icon: '🥔',
    description: 'Fresh tubers and roots including cassava, yams, sweet potatoes, and Irish potatoes.',
    subCategories: [
      { id: 'sub6', name: 'Cassava', slug: 'cassava', productCount: 145 },
      { id: 'sub7', name: 'Yams', slug: 'yams', productCount: 98 },
      { id: 'sub8', name: 'Sweet Potatoes', slug: 'sweet-potatoes', productCount: 76 },
      { id: 'sub9', name: 'Irish Potatoes', slug: 'irish-potatoes', productCount: 112 },
    ],
    productCount: 431,
    image: 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=800&h=400&fit=crop',
  },
  {
    id: 'cat3',
    name: 'Vegetables',
    slug: 'vegetables',
    icon: '🥬',
    description: 'Fresh vegetables including tomatoes, onions, peppers, and leafy greens from local farms.',
    subCategories: [
      { id: 'sub10', name: 'Tomatoes', slug: 'tomatoes', productCount: 189 },
      { id: 'sub11', name: 'Onions', slug: 'onions', productCount: 134 },
      { id: 'sub12', name: 'Peppers', slug: 'peppers', productCount: 98 },
      { id: 'sub13', name: 'Leafy Greens', slug: 'leafy-greens', productCount: 156 },
    ],
    productCount: 577,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop',
  },
  {
    id: 'cat4',
    name: 'Fruits',
    slug: 'fruits',
    icon: '🍎',
    description: 'Tropical and exotic fruits including mangoes, pineapples, avocados, and citrus fruits.',
    subCategories: [
      { id: 'sub14', name: 'Mangoes', slug: 'mangoes', productCount: 167 },
      { id: 'sub15', name: 'Avocados', slug: 'avocados', productCount: 134 },
      { id: 'sub16', name: 'Pineapples', slug: 'pineapples', productCount: 89 },
      { id: 'sub17', name: 'Citrus', slug: 'citrus', productCount: 112 },
      { id: 'sub18', name: 'Bananas', slug: 'bananas', productCount: 145 },
    ],
    productCount: 647,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=800&h=400&fit=crop',
  },
  {
    id: 'cat5',
    name: 'Livestock',
    slug: 'livestock',
    icon: '🐄',
    description: 'Quality livestock products including cattle, goats, sheep, poultry, and dairy products.',
    subCategories: [
      { id: 'sub19', name: 'Cattle', slug: 'cattle', productCount: 78 },
      { id: 'sub20', name: 'Goats', slug: 'goats', productCount: 65 },
      { id: 'sub21', name: 'Poultry', slug: 'poultry', productCount: 145 },
      { id: 'sub22', name: 'Dairy', slug: 'dairy', productCount: 89 },
    ],
    productCount: 377,
    image: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&h=400&fit=crop',
  },
  {
    id: 'cat6',
    name: 'Agro-inputs',
    slug: 'agro-inputs',
    icon: '🌱',
    description: 'Agricultural inputs including seeds, fertilizers, pesticides, and farming equipment.',
    subCategories: [
      { id: 'sub23', name: 'Seeds', slug: 'seeds', productCount: 234 },
      { id: 'sub24', name: 'Fertilizers', slug: 'fertilizers', productCount: 156 },
      { id: 'sub25', name: 'Pesticides', slug: 'pesticides', productCount: 98 },
      { id: 'sub26', name: 'Equipment', slug: 'equipment', productCount: 67 },
    ],
    productCount: 555,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=400&fit=crop',
  },
];

export const mockSupplierProfile: SupplierProfile = {
  id: 'v1',
  name: 'Green Valley Farms',
  rating: 4.8,
  totalSales: 15420,
  location: 'Nakuru, Kenya',
  isVerified: true,
  isQualityChecked: true,
  responseTime: '< 2 hours',
  description: 'Green Valley Farms is a leading agricultural producer in the Rift Valley region of Kenya. We specialize in premium coffee, fresh produce, and organic farming practices. With over 15 years of experience, we supply to both local and international markets.',
  coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=400&fit=crop',
  yearsInOperation: 15,
  capacity: '500 tons/year',
  productionMethods: ['Organic Farming', 'Sustainable Agriculture', 'Drip Irrigation', 'Integrated Pest Management'],
  certifications: [
    { id: 'cert1', name: 'Organic Certified', issuedBy: 'Kenya Organic Agriculture Network', validUntil: '2027-12-31', icon: '🌿' },
    { id: 'cert2', name: 'GlobalGAP', issuedBy: 'GlobalGAP', validUntil: '2026-06-30', icon: '✅' },
    { id: 'cert3', name: 'Fair Trade', issuedBy: 'Fairtrade International', validUntil: '2026-12-31', icon: '🤝' },
  ],
  socialLinks: {
    whatsapp: '+254712345678',
    facebook: 'greenvalleyfarms',
    instagram: 'greenvalleyfarms_ke',
    twitter: 'gvfarms_ke',
    website: 'https://greenvalleyfarms.co.ke',
  },
  activityPosts: [
    {
      id: 'post1',
      type: 'harvest',
      title: 'New Coffee Harvest Ready',
      content: 'Our premium Arabica coffee beans from the latest harvest are now available. Grade AA quality, perfect for export.',
      image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&h=400&fit=crop',
      createdAt: '2026-01-08T10:00:00Z',
    },
    {
      id: 'post2',
      type: 'price_update',
      title: 'Bulk Pricing Update',
      content: "We've updated our bulk pricing for orders above 500kg. Contact us for the best rates!",
      createdAt: '2026-01-05T14:30:00Z',
    },
    {
      id: 'post3',
      type: 'new_product',
      title: 'Introducing Organic Avocados',
      content: "We're excited to add organic Hass avocados to our product line. Export quality, available from February.",
      image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&h=400&fit=crop',
      createdAt: '2026-01-02T09:00:00Z',
    },
  ],
  gallery: [
    { id: 'g1', type: 'image', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop', caption: 'Our farm in the Rift Valley' },
    { id: 'g2', type: 'image', url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&h=600&fit=crop', caption: 'Premium coffee processing' },
    { id: 'g3', type: 'image', url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&h=600&fit=crop', caption: 'Fresh organic avocados' },
    { id: 'g4', type: 'image', url: 'https://images.unsplash.com/photo-1574323347407-f5e1c6c56e18?w=800&h=600&fit=crop', caption: 'Sustainable farming practices' },
  ],
};

export const mockReviews: Review[] = [
  {
    id: 'r1',
    buyerName: 'AfriTrade Foods Ltd',
    buyerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    rating: 5,
    comment: 'Excellent quality coffee beans! Fast delivery and great communication. Will definitely order again.',
    createdAt: '2026-01-05T10:00:00Z',
    productName: 'Premium Arabica Coffee Beans',
  },
  {
    id: 'r2',
    buyerName: 'Nairobi Fresh Markets',
    rating: 4,
    comment: 'Good quality avocados. Packaging could be improved for longer transport, but overall satisfied.',
    createdAt: '2025-12-28T14:30:00Z',
    productName: 'Fresh Organic Avocados',
  },
  {
    id: 'r3',
    buyerName: 'Export Solutions Ghana',
    buyerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    rating: 5,
    comment: 'Professional supplier with consistent quality. Their organic certification is a big plus for our export business.',
    createdAt: '2025-12-20T09:00:00Z',
    productName: 'Premium Arabica Coffee Beans',
  },
];

export const mockOrderTracking: OrderTracking = {
  orderId: 'ord1',
  orderNumber: 'HRV-2026-0107-001',
  currentStatus: 'processing',
  timeline: [
    {
      status: 'pending',
      title: 'Order Placed',
      description: 'Your order has been received and is being reviewed.',
      timestamp: '2026-01-07T10:30:00Z',
      isCompleted: true,
      isCurrent: false,
    },
    {
      status: 'confirmed',
      title: 'Order Confirmed',
      description: 'Payment verified. Order confirmed with vendors.',
      timestamp: '2026-01-07T11:15:00Z',
      isCompleted: true,
      isCurrent: false,
    },
    {
      status: 'processing',
      title: 'Processing',
      description: 'Vendors are preparing your order for shipment.',
      timestamp: '2026-01-08T09:00:00Z',
      isCompleted: false,
      isCurrent: true,
    },
    {
      status: 'shipped',
      title: 'Shipped',
      description: 'Your order is on its way.',
      timestamp: '',
      isCompleted: false,
      isCurrent: false,
    },
    {
      status: 'delivered',
      title: 'Delivered',
      description: 'Order delivered successfully.',
      timestamp: '',
      isCompleted: false,
      isCurrent: false,
    },
  ],
  vendorTracking: [
    {
      vendorId: 'v1',
      vendorName: 'Green Valley Farms',
      carrier: 'Vendor Delivery',
      estimatedDelivery: '2026-01-12',
      status: 'Processing',
    },
    {
      vendorId: 'v2',
      vendorName: 'Sunshine Agro Ltd',
      carrier: 'DHL Express',
      trackingNumber: 'DHL-1234567890',
      estimatedDelivery: '2026-01-11',
      status: 'Shipped',
    },
    {
      vendorId: 'v3',
      vendorName: 'Harvest Gold Exporters',
      estimatedDelivery: '2026-01-10',
      status: 'Ready for Pickup',
    },
  ],
};
